server:
  port: 8762
spring:
  application:
    #应用名称
    name: application-注册中心02
eureka:
  instance:

    appname: eureka
    #服务注册中心实例的主机名
    hostname: 127.0.0.1
    instance-id: 注册中心-02
    ip-address: 127.0.0.1
    #eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance
    lease-renewal-interval-in-seconds: 3
    #eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
    lease-expiration-duration-in-seconds: 6
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    #false 由于该应用为注册中心，所以设置为false,代表不向注册中心注册自己。
    fetch-registry: false
    healthcheck:
      enabled: true
  server:
    #eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
    eviction-interval-timer-in-ms: 3000
    #关闭自我保护机制 https://www.cnblogs.com/ericnie/p/9393995.html
    enable-self-preservation: false
info:
  app: 测试
  name: 测试
