server:
  port: 8769

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
#          search-locations: classpath:/shared
          search-locations: D:\test\config
  profiles:
    active: native
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
